# -*- coding: utf-8 -*-

"""
Jamdict POS mapping
"""

# This code is a part of jamdict-web library: https://github.com/neocl/jamdict-web
# :copyright: (c) 2021 Le Tuan Anh <tuananh.ke@gmail.com>
# :license: MIT, see LICENSE for more details.


JAMDICT_POS_MAP = {
    "'kari' adjective (archaic)": 'adj-kari',
    "'ku' adjective (archaic)": 'adj-ku',
    "'shiku' adjective (archaic)": 'adj-shiku',
    "'taru' adjective": 'adj-t',
    'Buddhist term': 'Buddh',
    'Godan verb - -aru special class': 'v5aru',
    'Godan verb - Iku/Yuku special class': 'v5k-s',
    'Godan verb - Uru old class verb (old form of Eru)': 'v5uru',
    "Godan verb with 'bu' ending": 'v5b',
    "Godan verb with 'gu' ending": 'v5g',
    "Godan verb with 'ku' ending": 'v5k',
    "Godan verb with 'mu' ending": 'v5m',
    "Godan verb with 'nu' ending": 'v5n',
    "Godan verb with 'ru' ending": 'v5r',
    "Godan verb with 'ru' ending (irregular verb)": 'v5r-i',
    "Godan verb with 'su' ending": 'v5s',
    "Godan verb with 'tsu' ending": 'v5t',
    "Godan verb with 'u' ending": 'v5u',
    "Godan verb with 'u' ending (special class)": 'v5u-s',
    "Godan verb with `bu' ending": 'v5b',
    "Godan verb with `gu' ending": 'v5g',
    "Godan verb with `ku' ending": 'v5k',
    "Godan verb with `mu' ending": 'v5m',
    "Godan verb with `nu' ending": 'v5n',
    "Godan verb with `ru' ending": 'v5r',
    "Godan verb with `ru' ending (irregular verb)": 'v5r-i',
    "Godan verb with `su' ending": 'v5s',
    "Godan verb with `tsu' ending": 'v5t',
    "Godan verb with `u' ending": 'v5u',
    "Godan verb with `u' ending (special class)": 'v5u-s',
    'Hokkaido-ben': 'hob',
    'Ichidan verb': 'v1',
    'Ichidan verb - kureru special class': 'v1-s',
    'Ichidan verb - zuru verb (alternative form of -jiru verbs)': 'vz',
    'Kansai-ben': 'ksb',
    'Kantou-ben': 'ktb',
    'Kuru verb - special class': 'vk',
    'Kyoto-ben': 'kyb',
    'Kyuushuu-ben': 'kyu',
    'Nagano-ben': 'nab',
    "Nidan verb (lower class) with 'bu' ending (archaic)": 'v2b-s',
    "Nidan verb (lower class) with 'dzu' ending (archaic)": 'v2d-s',
    "Nidan verb (lower class) with 'gu' ending (archaic)": 'v2g-s',
    "Nidan verb (lower class) with 'hu/fu' ending (archaic)": 'v2h-s',
    "Nidan verb (lower class) with 'ku' ending (archaic)": 'v2k-s',
    "Nidan verb (lower class) with 'mu' ending (archaic)": 'v2m-s',
    "Nidan verb (lower class) with 'nu' ending (archaic)": 'v2n-s',
    "Nidan verb (lower class) with 'ru' ending (archaic)": 'v2r-s',
    "Nidan verb (lower class) with 'su' ending (archaic)": 'v2s-s',
    "Nidan verb (lower class) with 'tsu' ending (archaic)": 'v2t-s',
    "Nidan verb (lower class) with 'u' ending and 'we' conjugation (archaic)": 'v2w-s',
    "Nidan verb (lower class) with 'yu' ending (archaic)": 'v2y-s',
    "Nidan verb (lower class) with 'zu' ending (archaic)": 'v2z-s',
    "Nidan verb (lower class) with `bu' ending (archaic)": 'v2b-s',
    "Nidan verb (lower class) with `dzu' ending (archaic)": 'v2d-s',
    "Nidan verb (lower class) with `gu' ending (archaic)": 'v2g-s',
    "Nidan verb (lower class) with `hu/fu' ending (archaic)": 'v2h-s',
    "Nidan verb (lower class) with `ku' ending (archaic)": 'v2k-s',
    "Nidan verb (lower class) with `mu' ending (archaic)": 'v2m-s',
    "Nidan verb (lower class) with `nu' ending (archaic)": 'v2n-s',
    "Nidan verb (lower class) with `ru' ending (archaic)": 'v2r-s',
    "Nidan verb (lower class) with `su' ending (archaic)": 'v2s-s',
    "Nidan verb (lower class) with `tsu' ending (archaic)": 'v2t-s',
    "Nidan verb (lower class) with `u' ending and `we' conjugation (archaic)": 'v2w-s',
    "Nidan verb (lower class) with `yu' ending (archaic)": 'v2y-s',
    "Nidan verb (lower class) with `zu' ending (archaic)": 'v2z-s',
    "Nidan verb (upper class) with 'bu' ending (archaic)": 'v2b-k',
    "Nidan verb (upper class) with 'dzu' ending (archaic)": 'v2d-k',
    "Nidan verb (upper class) with 'gu' ending (archaic)": 'v2g-k',
    "Nidan verb (upper class) with 'hu/fu' ending (archaic)": 'v2h-k',
    "Nidan verb (upper class) with 'ku' ending (archaic)": 'v2k-k',
    "Nidan verb (upper class) with 'mu' ending (archaic)": 'v2m-k',
    "Nidan verb (upper class) with 'ru' ending (archaic)": 'v2r-k',
    "Nidan verb (upper class) with 'tsu' ending (archaic)": 'v2t-k',
    "Nidan verb (upper class) with 'yu' ending (archaic)": 'v2y-k',
    "Nidan verb (upper class) with `bu' ending (archaic)": 'v2b-k',
    "Nidan verb (upper class) with `dzu' ending (archaic)": 'v2d-k',
    "Nidan verb (upper class) with `gu' ending (archaic)": 'v2g-k',
    "Nidan verb (upper class) with `hu/fu' ending (archaic)": 'v2h-k',
    "Nidan verb (upper class) with `ku' ending (archaic)": 'v2k-k',
    "Nidan verb (upper class) with `mu' ending (archaic)": 'v2m-k',
    "Nidan verb (upper class) with `ru' ending (archaic)": 'v2r-k',
    "Nidan verb (upper class) with `tsu' ending (archaic)": 'v2t-k',
    "Nidan verb (upper class) with `yu' ending (archaic)": 'v2y-k',
    "Nidan verb with 'u' ending (archaic)": 'v2a-s',
    'Osaka-ben': 'osb',
    'Ryuukyuu-ben': 'rkb',
    'Shinto term': 'Shinto',
    'Tosa-ben': 'tsb',
    'Touhoku-ben': 'thb',
    'Tsugaru-ben': 'tsug',
    "Yodan verb with 'bu' ending (archaic)": 'v4b',
    "Yodan verb with 'gu' ending (archaic)": 'v4g',
    "Yodan verb with 'hu/fu' ending (archaic)": 'v4h',
    "Yodan verb with 'ku' ending (archaic)": 'v4k',
    "Yodan verb with 'mu' ending (archaic)": 'v4m',
    "Yodan verb with 'nu' ending (archaic)": 'v4n',
    "Yodan verb with 'ru' ending (archaic)": 'v4r',
    "Yodan verb with 'su' ending (archaic)": 'v4s',
    "Yodan verb with 'tsu' ending (archaic)": 'v4t',
    "Yodan verb with `bu' ending (archaic)": 'v4b',
    "Yodan verb with `gu' ending (archaic)": 'v4g',
    "Yodan verb with `hu/fu' ending (archaic)": 'v4h',
    "Yodan verb with `ku' ending (archaic)": 'v4k',
    "Yodan verb with `mu' ending (archaic)": 'v4m',
    "Yodan verb with `nu' ending (archaic)": 'v4n',
    "Yodan verb with `ru' ending (archaic)": 'v4r',
    "Yodan verb with `su' ending (archaic)": 'v4s',
    "Yodan verb with `tsu' ending (archaic)": 'v4t',
    "`kari' adjective (archaic)": 'adj-kari',
    "`ku' adjective (archaic)": 'adj-ku',
    "`shiku' adjective (archaic)": 'adj-shiku',
    "`taru' adjective": 'adj-t',
    'abbreviation': 'abbr',
    'adjectival nouns or quasi-adjectives (keiyodoshi)': 'adj-na',
    'adjective (keiyoushi)': 'adj-i',
    'adjective (keiyoushi) - yoi/ii class': 'adj-ix',
    'adverb (fukushi)': 'adv',
    "adverb taking the 'to' particle": 'adv-to',
    "adverb taking the `to' particle": 'adv-to',
    'adverbial noun (fukushitekimeishi)': 'n-adv',
    'anatomical term': 'anat',
    'archaic/formal form of na-adjective': 'adj-nari',
    'archaism': 'arch',
    'architecture term': 'archit',
    'astronomy, etc. term': 'astron',
    'ateji (phonetic) reading': 'ateji',
    'auxiliary': 'aux',
    'auxiliary adjective': 'aux-adj',
    'auxiliary verb': 'aux-v',
    'baseball term': 'baseb',
    'biology term': 'biol',
    'botany term': 'bot',
    'business term': 'bus',
    'chemistry term': 'chem',
    "children's language": 'chn',
    'colloquialism': 'col',
    'computer terminology': 'comp',
    'conjunction': 'conj',
    'copula': 'cop-da',
    'counter': 'ctr',
    'derogatory': 'derog',
    'economics term': 'econ',
    'engineering term': 'engr',
    'exclusively kana': 'ek',
    'exclusively kanji': 'eK',
    'expressions (phrases, clauses, etc.)': 'exp',
    'familiar language': 'fam',
    'female term or language': 'fem',
    'finance term': 'finc',
    'food term': 'food',
    'geology, etc. term': 'geol',
    'geometry term': 'geom',
    'gikun (meaning as reading) or jukujikun (special kanji reading)': 'gikun',
    'honorific or respectful (sonkeigo) language': 'hon',
    'humble (kenjougo) language': 'hum',
    'idiomatic expression': 'id',
    'interjection (kandoushi)': 'int',
    'intransitive verb': 'vi',
    'irregular nu verb': 'vn',
    'irregular okurigana usage': 'io',
    'irregular ru verb, plain form ends with -ri': 'vr',
    'irregular verb': 'iv',
    'jocular, humorous term': 'joc',
    'law, etc. term': 'law',
    'linguistics terminology': 'ling',
    'mahjong term': 'mahj',
    'male slang': 'male-sl',
    'male term or language': 'male',
    'manga slang': 'm-sl',
    'martial arts term': 'MA',
    'mathematics': 'math',
    'medicine, etc. term': 'med',
    'military': 'mil',
    'music term': 'music',
    'noun (common) (futsuumeishi)': 'n',
    'noun (temporal) (jisoumeishi)': 'n-t',
    'noun or participle which takes the aux. verb suru': 'vs',
    'noun or verb acting prenominally': 'adj-f',
    'noun, used as a prefix': 'n-pref',
    'noun, used as a suffix': 'n-suf',
    "nouns which may take the genitive case particle 'no'": 'adj-no',
    "nouns which may take the genitive case particle `no'": 'adj-no',
    'numeric': 'num',
    'obscure term': 'obsc',
    'obsolete term': 'obs',
    'old or irregular kana form': 'oik',
    'onomatopoeic or mimetic word': 'on-mim',
    'out-dated or obsolete kana usage': 'ok',
    'particle': 'prt',
    'physics terminology': 'physics',
    'poetical term': 'poet',
    'polite (teineigo) language': 'pol',
    'pre-noun adjectival (rentaishi)': 'adj-pn',
    'prefix': 'pref',
    'pronoun': 'pn',
    'proper noun': 'n-pr',
    'proverb': 'proverb',
    'rare': 'rare',
    'rude or X-rated term (not displayed in educational software)': 'X',
    'sensitive': 'sens',
    'shogi term': 'shogi',
    'slang': 'sl',
    'sports term': 'sports',
    'su verb - precursor to the modern suru': 'vs-c',
    'suffix': 'suf',
    'sumo term': 'sumo',
    'suru verb - irregular': 'vs-i',
    'suru verb - special class': 'vs-s',
    'transitive verb': 'vt',
    'unclassified': 'unc',
    'verb unspecified': 'v-unspec',
    'vulgar expression or word': 'vulg',
    'word containing irregular kana usage': 'ik',
    'word containing irregular kanji usage': 'iK',
    'word containing out-dated kanji': 'oK',
    'word usually written using kana alone': 'uk',
    'word usually written using kanji alone': 'uK',
    'yojijukugo': 'yoji',
    'zoology term': 'zool'}
